from __future__ import annotations

from pathlib import Path
import argparse
import json
import re


SKIP_DIRS = {".git", ".pytest_cache", "__pycache__", ".mypy_cache", ".ruff_cache", "build", "dist", ".venv"}
GENERATED_DIR_SUFFIXES = (".egg-info", ".dist-info")
GENERATED_FILE_SUFFIXES = {".pyc", ".pyo"}
TEXT_EXTENSIONS = {"", ".md", ".ps1", ".py", ".txt", ".yml", ".yaml", ".json", ".toml"}
PRIVATE_PATH_PATTERNS = {
    "windows_user_path": re.compile(r"C:\\Users\\[A-Za-z0-9._ -]+", re.IGNORECASE),
    "wsl_windows_user_path": re.compile(r"/mnt/[a-z]/Users/[A-Za-z0-9._ -]+", re.IGNORECASE),
    "linux_home_path": re.compile(r"/home/[A-Za-z0-9._ -]+"),
}
PRIVATE_MARKERS = [
    "Hetzner" + "Logs",
    "api_trade" + "_executor.py",
    "api_telegram" + "_bot.py",
    "upscalp" + "-api",
    "upscalp" + "-scanner",
    "upscalp" + "-sender",
    "upscalp" + "-admin",
    "CanonicalGroupLimited.Ubuntu" + "_79rhkp1fndgsc",
]
TOKEN_PATTERNS = {
    "openai_api_key_like": re.compile(r"sk-[A-Za-z0-9_-]{20,}"),
    "github_token_like": re.compile(r"gh[pousr]_[A-Za-z0-9_]{20,}"),
    "netlify_token_like": re.compile(r"nfp_[A-Za-z0-9]{20,}"),
}


def scan(root: Path) -> dict[str, object]:
    root = root.resolve()
    failures: list[dict[str, str]] = []
    scanned_files = 0
    for path in root.rglob("*"):
        rel_parts = path.relative_to(root).parts
        has_generated_parent = any(
            part in SKIP_DIRS or part.endswith(GENERATED_DIR_SUFFIXES)
            for part in rel_parts[:-1]
        )
        if path.is_dir() and (path.name in SKIP_DIRS or path.name.endswith(GENERATED_DIR_SUFFIXES)):
            failures.append({
                "file": str(path.relative_to(root)),
                "kind": "generated_artifact",
                "marker": "generated/cache/build/metadata directory",
            })
            continue
        if not path.is_file() or has_generated_parent:
            continue
        if path.suffix in GENERATED_FILE_SUFFIXES:
            failures.append({
                "file": str(path.relative_to(root)),
                "kind": "generated_artifact",
                "marker": "generated bytecode file",
            })
            continue
        if path.suffix not in TEXT_EXTENSIONS and path.name not in {"LICENSE"}:
            continue
        scanned_files += 1
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rel = str(path.relative_to(root))
        for name, pattern in PRIVATE_PATH_PATTERNS.items():
            if pattern.search(text):
                failures.append({"file": rel, "kind": "private_marker", "marker": name})
        for marker in PRIVATE_MARKERS:
            if marker in text:
                failures.append({"file": rel, "kind": "private_marker", "marker": marker})
        for name, pattern in TOKEN_PATTERNS.items():
            if pattern.search(text):
                failures.append({"file": rel, "kind": name, "marker": "token-shaped string"})
    return {"ok": not failures, "root": str(root), "scanned_files": scanned_files, "failures": failures}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="audit_public_package.py")
    parser.add_argument("--root", default=".", help="Package root to audit")
    args = parser.parse_args(argv)
    result = scan(Path(args.root))
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result["ok"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
